#!/usr/bin/env bash
# Install FXOS as a systemd service (non-Docker deployment)
# Builds the binary from source, then installs as a systemd service.
#
# Usage:
#   sudo ./scripts/install-nodocker.sh
#
# Prerequisites (auto-checked, will bail if missing):
#   - Go 1.26+ (go.mod requires 1.26.5)
#   - git, make, gcc, g++, curl
#   - openssl (only needed to generate a fresh .env on first install)

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[install]${NC} $*"; }
warn() { echo -e "${YELLOW}[install]${NC} $*"; }
err()  { echo -e "${RED}[install]${NC} $*" >&2; }

pkg_install() {
  if command -v apt-get &>/dev/null; then
    apt-get install -y "$@"
  elif command -v dnf &>/dev/null; then
    dnf install -y "$@"
  elif command -v yum &>/dev/null; then
    yum install -y "$@"
  else
    err "No supported package manager found (apt-get/dnf/yum)."
    exit 1
  fi
}

# Map package names across distros (CentOS uses gcc-c++, Debian uses g++)
pkg_cxx() {
  if command -v apt-get &>/dev/null; then
    echo "g++"
  else
    echo "gcc-c++"
  fi
}

if [[ $EUID -ne 0 ]]; then
  err "Must run as root: sudo $0"
  exit 1
fi

INSTALL_DIR="/opt/fxos"
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# ── Sanity: must run from the repository checkout ───────────
if [[ ! -f "$SCRIPT_DIR/go.mod" ]]; then
  err "go.mod not found next to this script — run it from the repo checkout:"
  err "  sudo ./scripts/install-nodocker.sh"
  exit 1
fi

# ── Check dependencies ──────────────────────────────────────
log "Checking dependencies..."

missing=()

command -v go &>/dev/null || missing+=("go")
command -v git &>/dev/null || missing+=("git")
command -v make &>/dev/null || missing+=("make")
command -v gcc &>/dev/null || missing+=("gcc")
command -v g++ &>/dev/null || missing+=("$(pkg_cxx)")
command -v curl &>/dev/null || missing+=("curl")
command -v openssl &>/dev/null || missing+=("openssl")

if [[ ${#missing[@]} -gt 0 ]]; then
  log "Installing missing dependencies: ${missing[*]}"
  pkg_install "${missing[@]}"
fi

# Check Go version >= 1.26 (go.mod requires 1.26.5)
# Portable extraction (no grep -P): "go1.26.5 linux/amd64" -> "1.26"
GO_VER=$(go version | awk '{print $3}' | sed 's/^go//' | cut -d. -f1-2)
GO_MAJOR="${GO_VER%%.*}"
GO_MINOR="${GO_VER##*.}"
if (( GO_MAJOR < 1 || (GO_MAJOR == 1 && GO_MINOR < 26) )); then
  err "Go 1.26+ required, found $GO_VER"
  exit 1
fi
log "  Go $GO_VER ✓"

# ── Build binary ────────────────────────────────────────────
log "Building fxos binary..."
cd "$SCRIPT_DIR"
# Remove any stale binary first so a failed build can't be mistaken for success
rm -f fxos
CGO_ENABLED=1 GOOS=linux go build -trimpath -ldflags="-s -w" -o fxos .

if [[ ! -x fxos ]]; then
  err "Build failed."
  exit 1
fi
log "  Build succeeded ✓"

# ── Create service user ─────────────────────────────────────
if ! id -u fxos &>/dev/null; then
  log "Creating fxos user..."
  useradd --system --no-create-home --shell /usr/sbin/nologin fxos
fi

# ── Install binary ──────────────────────────────────────────
log "Installing to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR/data"
cp "$SCRIPT_DIR/fxos" "$INSTALL_DIR/fxos"
chmod 755 "$INSTALL_DIR/fxos"

# ── Ensure .env exists (JWT/DATA_ENCRYPTION/RSA are required — the
#    backend refuses to start without them, see config.MustInit) ──
if [[ ! -f "$INSTALL_DIR/.env" ]]; then
  if [[ -f "$SCRIPT_DIR/.env" ]]; then
    cp "$SCRIPT_DIR/.env" "$INSTALL_DIR/.env"
    chmod 600 "$INSTALL_DIR/.env"
    log "Copied .env to $INSTALL_DIR/"
  else
    warn "No .env found in the repo — generating one with fresh keys."
    JWT_SECRET=$(openssl rand -base64 32)
    DATA_ENCRYPTION_KEY=$(openssl rand -base64 32)
    # Single-line PEM with literal \n escapes — matches the backend contract
    # (crypto.go replaces "\n" with a real newline before PEM decoding)
    RSA_PRIVATE_KEY=$(openssl genrsa 2048 2>/dev/null | tr '\n' '\\' | sed 's/\\/\\n/g' | sed 's/\\n$//')
    cat > "$INSTALL_DIR/.env" <<EOF
# FXOS Configuration (Auto-generated by install-nodocker.sh)
JWT_SECRET=${JWT_SECRET}
DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY}
RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
TZ=Asia/Shanghai
EOF
    chmod 600 "$INSTALL_DIR/.env"
    log "  Generated $INSTALL_DIR/.env (JWT_SECRET, DATA_ENCRYPTION_KEY, RSA_PRIVATE_KEY)"
    warn "  Review it and rotate keys before exposing this server publicly."
  fi
else
  log "  .env already exists at $INSTALL_DIR/.env, keeping it"
fi

# ── Set ownership ───────────────────────────────────────────
chown -R fxos:fxos "$INSTALL_DIR"
chmod 770 "$INSTALL_DIR/data"

# ── Install systemd unit ───────────────────────────────────
log "Installing systemd service..."
cp "$SCRIPT_DIR/scripts/fxos.service" /etc/systemd/system/fxos.service
systemctl daemon-reload

# ── Enable and start ────────────────────────────────────────
systemctl enable fxos.service
systemctl start fxos.service

# Wait for the service to be healthy (up to 15s). Checking only
# `systemctl is-active` is unreliable with Restart=always — a crash
# loop briefly reports active. Verify the health endpoint instead.
ok=0
for _ in $(seq 1 15); do
  if curl -fsS --max-time 2 http://127.0.0.1:8080/api/health >/dev/null 2>&1; then
    ok=1
    break
  fi
  sleep 1
done

if [[ "$ok" -eq 1 ]]; then
  log "FXOS service is running (health check OK)."
  systemctl status fxos.service --no-pager || true
else
  err "Service not healthy. Check: journalctl -u fxos -n 50"
  systemctl status fxos.service --no-pager || true
  exit 1
fi

log ""
log "Installed successfully. Useful commands:"
log "  systemctl status fxos     # check status"
log "  systemctl restart fxos    # restart"
log "  systemctl stop fxos       # stop"
log "  journalctl -u fxos -f     # tail logs"
log ""
log "Note: this installs the backend only. The web frontend (web/dist) is"
log "served separately — build it and point your web server (nginx) at it,"
log "proxying /api to http://127.0.0.1:8080."
